[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
decorations = "Buttonless"
padding = {x = 5, y = 35}
dynamic_padding = true
opacity = 0.7
blur = true

[font]
normal = {family = "Hack Nerd Font", style = "Regular"}
bold = {family = "Hack Nerd Font", style = "Regular"}
italic = {family = "Hack Nerd Font", style = "Regular"}
bold_italic = {family = "Hack Nerd Font", style = "Regular"}
size = 13

[colors]
transparent_background_colors = true
